
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
       BufferedImage myImage;
        try {
            myImage = ImageIO.read(new File("wintry.png"));
            this.setContentPane(new ImagePanel(myImage));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        // elsewhere
        
         initComponents();
    }
    
    class ImagePanel extends JComponent {
        private Image image;
        public ImagePanel(Image image) {
            this.image = image;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(image, 0, 0, this);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ND.COM\\Desktop\\SnowGameFull\\snowman.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 260, 76, 97);
        jLabel1.setLocation(300, 260);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ND.COM\\Desktop\\SnowGameFull\\snowflake2.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 40, 40, 40);
        jLabel3.setLocation(400, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ND.COM\\Desktop\\SnowGameFull\\snowflake1.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 35, 35);
        jLabel2.setLocation(200, 10);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("GAME OVER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 150, 300, 70);
        jLabel4.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Score : "+snowMan.snowflakesCatched);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel5.setVisible(true);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(580, 310, 90, 30);

        pack();
    }//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
//        System.out.println(evt.getKeyChar());        
        if(isGameOver) return;
        if(evt.getKeyCode() == 37) { // Left         
            this.snowMan.moveLeft();
            jLabel1.setLocation(this.snowMan.x, this.snowMan.y);
        } else if(evt.getKeyCode() == 39) { // Right
            this.snowMan.moveRight();
            jLabel1.setLocation(this.snowMan.x, this.snowMan.y);
        }      
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void showGUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        final MainWindow window = new MainWindow();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                window = new MainWindow();
                window.setVisible(true);
            }
        });
        
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
        
            @Override
            public void run() {
                window.moveSnowFlakes();
            }
          }, 0, 500);

          // Since Java-8
//        timer.scheduleAtFixedRate(() -> , 2*60*1000, 2*60*1000);
    }
    
    SnowMan snowMan = new SnowMan(300, 260, this);
    SnowFlake snow1 = new SnowFlake(400, 0);
    SnowFlake snow2 = new SnowFlake(200, 0);
    
    boolean isGameOver = false;
    
    public void gameOver() {
        isGameOver = true;
        jLabel4.setVisible(isGameOver);
    }
    
    public void moveSnowFlakes() {
        if(isGameOver) return;
        snow1.fall();
        snow2.fall();
        
        // 330 is last y
        Rectangle snowManRect = new Rectangle(snowMan.x,snowMan.y,jLabel1.getWidth(),jLabel1.getHeight());
        Rectangle snow1Rect = new Rectangle(snow1.x,snow1.y,jLabel3.getWidth(),jLabel3.getHeight());
        Rectangle snow2Rect = new Rectangle(snow2.x,snow2.y,jLabel2.getWidth(),jLabel2.getHeight());
        
        // Assuming there is an intersect method, otherwise just handcompare the values
        if (snowManRect.intersects(snow1Rect)) {
            int randomNum = ThreadLocalRandom.current().nextInt(10, 400 + 1);
            snow1.reset(randomNum);
            snowMan.catchSnowflake();
            jLabel5.setText("Score: "+snowMan.snowflakesCatched);
        }
        
        if (snowManRect.intersects(snow2Rect)) {
            int randomNum = ThreadLocalRandom.current().nextInt(10, 400 + 1);
            snow2.reset(randomNum);
            snowMan.catchSnowflake();
            jLabel5.setText("Score: "+snowMan.snowflakesCatched);
        }
        
        if (snow1.y >= 330) {
            int randomNum = ThreadLocalRandom.current().nextInt(10, 400 + 1);
            snow1.reset(randomNum);
            snowMan.missSnowflake();
        }
        
        if (snow2.y >= 330) {
            int randomNum = ThreadLocalRandom.current().nextInt(10, 400 + 1);
            snow2.reset(randomNum);
            snowMan.missSnowflake();
        }
        
        jLabel3.setLocation(snow1.x, snow1.y);
        jLabel2.setLocation(snow2.x, snow2.y);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
